apiVersion: fn.kpt.dev/v1alpha1
kind: Replacements
metadata: # kpt-merge: /ensure-rbac
  name: ensure-rbac
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: ConfigMap
      name: kptfile.kpt.dev
      fieldPath: data.group
    targets:
      - select:
          kind: RoleBinding
          name: app-admin
        fieldPaths:
          - subjects.[kind=Group].name
        options:
          create: true
