# RoleBinding binds the service account created in this namespace
# and users belonging to specified group for tenant.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata: # kpt-merge: example/app-admin
  name: app-admin
  namespace: example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-admin
subjects:
- kind: ServiceAccount
  name: sa
  namespace: example
- kind: Group
  name: example-app-admin@acme.com
