apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /set-namespace
  name: set-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
source: |-
  def set_namespace(resource_list):
     set_ns = ""
     num_ns = 0
     for r in resource_list["items"]:
       if r["apiVersion"] == "v1" and r["kind"] == "ConfigMap" and r.get("metadata").get("name") == "kptfile.kpt.dev":
         set_ns = r["data"]["name"]
       if r["apiVersion"] == "v1" and r["kind"] == "Namespace":
         num_ns +=1

     if num_ns > 1:
        fail("pkg must contain one namespace resource")

     if set_ns == "": # missing package context
       return

     for r in resource_list["items"]:
       if r["apiVersion"] == "v1" and r["kind"] == "Namespace":
         r["metadata"]["name"] = set_ns
       if r["metadata"].get("namespace", "") != "":
         r["metadata"]["namespace"] = set_ns
       if r.get("kind") == "RoleBinding" and r.get("metadata").get("namespace") != "":
       # namespace scoping
         for subject in r.get("subjects", []):
           if subject.get("namespace", "") != "":
              subject["namespace"] = set_ns

  set_namespace(ctx.resource_list)
